### ISSUE TITLE
Please 1.20.1 :)

### ISSUE THREAD

**Issue by DrakonFG** [Cozary/rideable_zombie_horses#1]
Update it to  1.20.1

**Comment by Cozary** [comment]
Hi! Even though I created the mod, it belongs to ArcaneAlloy. So it is he who should be asked for the update.

**Comment by DrakonFG** [comment]
?? But i sugested the improviment where the mod page pointed to do... ????

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
